### ISSUE TITLE
Remove Model for Registrant from controllers

### ISSUE THREAD

**Issue by domfarolino** [RevolutionUC/revolutionuc-website#129]
Hey @kurtlewis would you mind re-submitting https://github.com/RevolutionUC/revolutionuc-website/pull/66 for the new 2018 site? The API could still use that change, and I figured it would be best to scrap everything before the 2018 changes since so much has been modified. (If not no worries, I just know that was an outstanding PR [my bad]).

**Comment by kurtlewis** [comment]
Yeah I'll take a look at it!

**Comment by domfarolino** [comment]
Coolio thank ya

**Comment by domfarolino** [comment]
Actually took care of this via #148
