### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by domfarolino** [RevolutionUC/revolutionuc-website#18]
Registration needs to happen. I figure we first need to get a list of all the content we'll be collecting. This will help us hammer out the specifics of the form and then the backend.

## Mandatory fields

- [x] **first name**
- [x] **last name**
- [x] **email address**
- [x] **school**
  - [ ] autofill schools that have already been submitted to avoid duplication of same school but different spelling or casing
- [x] **date of birth**
- [x] **major**
- [x] **level of study** (high school, undergrad, grad)
- [x] **gender**
- [x] **phone number** 
- [x] **resume** (file upload)
- [x] **Time they registered** This is something we do behind the scenes, not something they do
- [x] **shirt size**
- [x] [**MLH data sharing notice agreement**](https://github.com/MLH/mlh-policies/blob/master/data-sharing.md)
- [x] [**agree to MLH Code of conduct**](https://static.mlh.io/docs/mlh-code-of-conduct.pdf)
- [x] **special accommodations**
- [x] **food restrictions** (allergies, vegan, vegetarian)

### Extra:

- [x] race/ethnicity
  - [x] American Indian or Alaskan Native
  - [x] Asian
  - [x] Black or African American
  - [x] Native Hawaiian or other Pacific Islander
  - [x] White
  - [x] Hispanic or Latino
- [x] how many hackthons have you been to?
- [x] How did you hear about RevolutionUC?
- [x] GitHub username

### Stuff we need to know before the event but not necessarily during registration:

- [x] ~~other medical conditions~~ special accommodations (see above)
- [x] ~~did they confirm their attendance~~ email verification (waiting on https://github.com/RevolutionUC/revolutionuc-emails/issues/13)
- [x] ~~did they actually show up~~ have they been checked in (day-of)

/cc @kurtlewis @noahbass

**Comment by noahbass** [comment]
Via @zacharysang:

-first name*
-last name*
-email address*
-school* (would be super if we could autofill schools that have already been submitted to avoid duplication of same school but different spelling or casing)
-date of birth*
-major
-level of study (high school, undergrad, grad)
-gender
-pronoun
-phone number
-race/ethnicity
-resume (file upload)

Stuff we need to know before the event but not necessarily during registration:
-food restrictions (allergies, vegan, vegetarian)
-shirt size
-other medical conditions

-did they actually show up

Also:

-how many hackthons have you been to?
-Github username

**Comment by kurtlewis** [comment]
I updated the original issue with a list, including Noah's additions. You'll note some things you might not think are necessary have been bolded - if the field is on MLH's form I marked it as mandatory so we at least have all the information they have. 

I also think the easiest thing to do is take all the information possible during registration - I think reaching out later with things like "Do you have any allergies?" presents two problems:
1. People who have allergies thinking we forgot about them during registration, and emailing us to tell us, which reflects poorly on us.
2. People not seeing the second email. If its on the registration from then its on them for missing it 100%

**Comment by noahbass** [comment]
Agree with @kurtlewis on the food restriction question. Asking for that info during registration is best.

**Comment by zacharysang** [comment]
Sounds good

**Comment by kurtlewis** [comment]
@zacharysang One thing Shy recommended we do is use the MLH system as a tool to help with that. Basically if they've filled out MLH's data it will auto populate our form. Now I don't know any of the specifics of something like that but its an option.

**Comment by isiah-lloyd** [comment]
The `school` field could autocomplete using this database: https://inventory.data.gov/dataset/032e19b4-5a90-41dc-83ff-6e4cd234f565/resource/38625c3d-5388-4c16-a30f-d105432553a4

**Comment by noahbass** [comment]
Email verification template added via https://github.com/RevolutionUC/revolutionuc-emails/issues/14
