### ISSUE TITLE
Styles & Redesign

### ISSUE THREAD

**Issue by domfarolino** [RevolutionUC/revolutionuc-website#2]
ALL STYLES ARE TEMPORARY AS OF NOW. We need to decide on a lot of styles though for the permanent site before we really move on. This will be a living issue with added boxes below as we come up with more things to make pretty. Yay.

 - [x] Font (@zcollins0 @noah did we decide on this in slack?)
 - [x] Header color
 - [x] Header nav link size (@zacharysang)
 - [x] Masthead picture recommendations
 - [x] Masthead picture styles (color)
 - [x] Get rid of MD-style content cards (@kurtlewis ?). These were just for my testing unless we want to keep them or something.

**Comment by noahbass** [comment]
👍  color masthead picture
👍  getting rid of the md style cards (or making them look less angulary)

Heading font is [jockey one](https://fonts.google.com/specimen/Jockey+One). Body font is undecided I think?

**Comment by domfarolino** [comment]
@zacharysang I added a box for "Header nav link size" Any font size recommendations? I don't have an eye for style and am cool with pretty much whatever so if anyone wants to have a say....go ahead.

**Comment by domfarolino** [comment]
## Everyone

I chose a header background color at random but it doesn't quite match our scheme (though it is kind of close). I suggest you open up DevTools in Chrome or some browser, use the element selector to highlight the header element and click on the little square of color:
![picker](https://cloud.githubusercontent.com/assets/9669289/21734125/c6784ed6-d42f-11e6-9aa6-ac043560f2b0.png)

Use the color picker to find a color you like. For those who don't know, the color picker allows you to move the mouse around on screen and choose a color that appears somewhere on the page. If you want to do this and maybe select some colors inside the revuc logo go ahead and make some recommendations on what the header bg color should be, be my guest. I just need a final color to go with. @kurtlewis your input would be good too.

**Comment by domfarolino** [comment]
Would welcome masthead picture recommendations. Please post links of pics found in the RevUC Fall 2016 Facebook album

**Comment by kurtlewis** [comment]
@domfarolino I've got a couple I've picked out as some nice ones to try. http://imgur.com/a/IL3Kh

I'm not sure if imgur compress much or not but I've got the originals if you like any of these

**Comment by noahbass** [comment]
More possible masthead pics:

https://drive.google.com/file/d/0B7lsGziuq3APRDNGQXkxdWtxelk/view?usp=sharing
https://drive.google.com/file/d/0B7lsGziuq3APT1ZXZTFqdWx5bDQ/view?usp=sharing

**Comment by domfarolino** [comment]
Gotta pixel recommendation? 500px now

**Comment by noahbass** [comment]
Between 600px to 700px - maybe even larger on some devices
