### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by zacharysang** [RevolutionUC/revolutionuc-website#35]
When scrolling down and using the navbar, then the new page does not scroll back up to the top. Instead, the new page will open up scrolled to somewhere in the middle

**Comment by domfarolino** [comment]
Could just rip the user up to the top of the screen whenever they click on a nav link? @noahbass

**Comment by domfarolino** [comment]
Fixed this in the registration Pr. Issue will close when registration merges

**Comment by domfarolino** [comment]
added registration milestone which closes this issue
