### ISSUE TITLE
Photo changes

### ISSUE THREAD

**Issue by zacharysang** [RevolutionUC/revolutionuc-website#37]
- [ ] Focus point on home 
- [ ] More women in pictures

**Comment by kurtlewis** [comment]
Possible pictures include:

![image](https://cloud.githubusercontent.com/assets/4043087/22005717/8a3c1734-dc33-11e6-833d-f7606776a1dc.png)
![image](https://cloud.githubusercontent.com/assets/4043087/22005728/9fc78a3e-dc33-11e6-898d-bea1cf1439fc.png)

If we want either of these let me know and I'll get the high quality water-mark free version. I haven't looked through the pictures from the spring - these are just fall

**Comment by domfarolino** [comment]
In my opinion those pictures look terrible lol. It sucks that the main pictures we have with women in them are pretty bad. I guess we can look for others though. @noahbass opinions?

**Comment by zacharysang** [comment]
I don't like the first one, but I think the second one is fine. What issues did you have with that one?

**Comment by domfarolino** [comment]
I guess its def the better of the two, but it seems dingy. Idc what we go with tho

**Comment by domfarolino** [comment]
Where do we want these posted anyways? Masthead?

**Comment by zacharysang** [comment]
I dont think masthead, maybe on the about page or on the faq when that goes
up? On the about page it could go in as new content to break up the text
even more, or could also replace one of the pics for Build. Learn. Grow

**Comment by domfarolino** [comment]
@RevolutionUC/web-team I'm assuming some of these pictures have been taken care of in the new frontend site right?

**Comment by noahbass** [comment]
Yeah, this can be closed.
