### ISSUE TITLE
Text in footer

### ISSUE THREAD

**Issue by zcollins0** [RevolutionUC/revolutionuc-website#39]
The text in the footer is hard to read. The white on blue is a bit difficult, but I don't think we can get a better font color. I would try increasing the font size by like half a point.

**Comment by domfarolino** [comment]
`font-size: 15px` => `font-size: 16px`

**Comment by domfarolino** [comment]
@zcollins0 why close? I assigned to noah

**Comment by zcollins0** [comment]
Missed the "assigned to noah" lol
