### ISSUE TITLE
Home page card does not trigger animation

### ISSUE THREAD

**Issue by isiah-lloyd** [RevolutionUC/revolutionuc-website#40]
The `.buildlearngrow-card` does not trigger a pretty animation like the links in the navbar. I don't know how big of a deal this is, just wanted to let you know.

**Comment by domfarolino** [comment]
Yes was gonna take care of it. Should be a quick fix thanks

**Comment by domfarolino** [comment]
Commit in registration PR takes care of this - will auto-close when registration is merged
