### ISSUE TITLE
Firefox: will-change memory consumption too high

### ISSUE THREAD

**Issue by domfarolino** [RevolutionUC/revolutionuc-website#55]
Crazy performance issues at play. Needs fixed.

**Comment by domfarolino** [comment]
I don't have any transition issues anymore on Linux, and it happens about 10% of the time on mac. @kurtlewis do you notice any page transition issues anymore on FF? I'm wondering if this got sorted out on FF's end and is no longer necessary to deal with for us. The fact that we only have two `will-change` properties in all of our CSS makes me think this is not something we need to optimize for.

**Comment by kurtlewis** [comment]
Yeah, I have noticed some issues. But I was having other problems with firefox this weekend so I'm not sure if they're actually the fault of the site. I'll keep an eye on it this week and try to remember to update you if I see anything.

(Funny story, firefox was consuming 1.9 GB of ram for 8 tabs on me yesterday, and 1.4 after I closed it entirely)

**Comment by domfarolino** [comment]
I believe this has been optimized in FF
