### ISSUE TITLE
Sponsor Page

### ISSUE THREAD

**Issue by isiah-lloyd** [RevolutionUC/revolutionuc-website#57]
Logos of sponsors on page.

Is there a certain order the logos should go in? Do higher tier sponsors get a more prominent logo?

**Comment by domfarolino** [comment]
Yes @zcollins0 or someone or @zacharysang will tell u

**Comment by zcollins0** [comment]
Yes, the higher the sponsor the higher and bigger the logo. If you can find it, reference last year's site. Or the t-shirt.
