### ISSUE TITLE
Devposts

### ISSUE THREAD

**Issue by kurtlewis** [RevolutionUC/revolutionuc-website#58]
We need to have a place  where the previous devposts, and eventually the new one, are put. There are a couple of requests from sponsorship and marketing to make past hacks available for outreach purposes. 

This is a medium priority issue. I'm aware this is on a separate issue but I'm making it more high visibility.

**Comment by kurtlewis** [comment]
Move devposts to below tagline image and above social media? @domfarolino @noahbass thoughts? Seems out of place to me with where they are now?

(sorry Dom for being nitpicky)

**Comment by domfarolino** [comment]
Check live changes
