### ISSUE TITLE
Waitlist

### ISSUE THREAD

**Issue by kurtlewis** [RevolutionUC/revolutionuc-website#59]
We need to have the functionality available that once we hit 550 registrants, we can switch from "registration" to "wait list."

The wait list differs from registration in the following ways: 
-  At the top of the registration form there is a disclaimer that we have hit capacity and they are signing up for the wait list, but that they should still register in case spots open up
- The email that people who have signed up received notifies them that they should monitor the email for notification that they have been accepted to the event.
- It should reiterate the above once they've verified their emails

**Comment by kurtlewis** [comment]
We also need a way to seperate waitlisted folks on the database. We also need to order people who have signed up by waitlist. This could be in the form of recording the time they registered, or actually attaching a number to them.

**Comment by domfarolino** [comment]
@noahbass Do we have a "you've been accepted" email template?

**Comment by noahbass** [comment]
Not yet. Working on it.

**Comment by noahbass** [comment]
"You've been accepted" template is available on `v1.1.8` at https://github.com/RevolutionUC/revolutionuc-emails
