### ISSUE TITLE
Schedule

### ISSUE THREAD

**Issue by kurtlewis** [RevolutionUC/revolutionuc-website#61]
We'll need to put the schedule up on the website sooner or later, probably first or second week of March. This means having styles and page ready for inserting the actual schedule.

**Comment by isiah-lloyd** [comment]
Tentative Schedule: https://docs.google.com/spreadsheets/d/11UyHbkuU0GPRJTyF4LE5VLIy9EP6Rd25-ElAbHKER7k/edit?usp=sharing
