### ISSUE TITLE
Mandatory Content

### ISSUE THREAD

**Issue by domfarolino** [RevolutionUC/revolutionuc-website#8]
## Mandatory content sorted by priority

Everyone, please make whatever contributions to this content issue you can and we'll slowly check the below boxes until we're finished ;)

 - [x] MLH Badge (see #3) (<-- assigned to @domfarolino)
 - [x] Link to MLH code of conduct
 - [x] Date (April 8th and 9th, 2017)
 - [x] mailto: address for potential sponsors (info@revolutionuc.com? @kurtlewis )
 - [x] mailto: address for general questions (info@revolutionuc.com)
 - [x] What is RevolutionUC
 - [x] What is a hackathon (rlly)

**Comment by kurtlewis** [comment]
### What is a hackathon
We definitely need this, considering how many people that come are first time participants. It can be in the FAQ (which is where it was in 2016). That combined with an explanation of what revolutionUc is should be adequate.

### Location
Just put 801 Rhodes Hall, University of Cincinnati.

### 2016 Site 
I'm up in the air about a link to the 2016 site. Certainly not necessary but if we linked to it with the previous devposts, itd be a cool think. Ultimately your call @domfarolino 

I'd be happy to help, but I'm probably not too useful... still if you see something here you'd like me to take a stab at, @ me

**Comment by domfarolino** [comment]
Low hanging fruit like small dev changes and content additions are welcome by anyone. If I see something for you specifically I'll let you know, else if you want to pick up an issue (or parts of one) be my guest, could use help.

**Comment by kurtlewis** [comment]
I'm working on the FAQ right now, largely copying things from the old FAQ

**Comment by domfarolino** [comment]
@kurtlewis FAQ is probably lower priority than other stuff since we can get on the MLH site without it I believe

**Comment by kurtlewis** [comment]
@domfarolino good call. I'm switching to the about page.

Items 2-7

**Comment by domfarolino** [comment]
Updated the checkboxes to match what @kurtlewis has put in his PR (thanks btw). Two more boxes and we're on the MLH site. I'll go and add the date to the main page.

**Comment by domfarolino** [comment]
@kurtlewis just double checking, this can be closed now right? Given your PR?

**Comment by kurtlewis** [comment]
@domfarolino Yeah since you created a new issue for the other stuff we can close this
